### ISSUE TITLE
[Bug Report] Error: Unknown column 'NaN' in 'where clause'

### ISSUE THREAD

**Issue by cumt-robin** [cumt-robin/fullstack-blog#40]
**Describe the bug**
```
/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packets/packet.js:728
    const err = new Error(message);
                ^

Error: Unknown column 'NaN' in 'where clause'
    at Packet.asError (/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/usr/src/fullstack-blog/app/backend/node_modules/.pnpm/mysql2@3.10.1/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'NaN' in 'where clause'",
  sql: 'SELECT id, article_name FROM article WHERE id in ((SELECT id FROM article WHERE private = 0 AND deleted = 0 AND id < NaN ORDER BY id DESC limit 1), (SELECT id FROM article WHERE private = 0 AND deleted = 0 AND id > NaN ORDER BY id asc limit 1))'
}
```

**Comment by cumt-robin** [comment]
对 id 需要进行校验
